### PR TITLE
ci: fix workflow, add matrix

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
@cade-vs I've tried a few different things to get this working, but still having troubles. You might wanna just merge this and then make any changes you find necessary.

With regard to the clang `ftlo=auto` error, have a look at this for a possible fix:

https://github.com/bbonev/yascreen/commit/59a83fdcaa6cb72ebe1fc3f939c7d99fea024a94

**Comment by LarryDC** [comment]
Good night Andy,

On Mon, 06 Feb 2023 17:49:03 -0800

Andy Alt ***@***.***> wrote among other things:

***@***.*** I've tried a few different things to get this working, but
|still having troubles. You might wanna just merge this and then make
|any changes you find necessary.
|
|With regard to the clang `ftlo=auto` error, have a look at this for
|a possible fix:
|
|https://github.com/bbonev/yascreen/commit/59a83fdcaa6cb72ebe1fc3f939c7d99fea024a94
|

My 2 cents:

All that was necessary was add a line to: 
"./pull-and-build-vfu.sh"

To compile both vfu & vfu.yas here (On Debian Testing) I just added
the line:

sudo make install -C yascreen

after the line:

make -C yascreen

Or if that's not clear. The make lines at the end of the file  should
be:

make -C yascreen
sudo make install -C yascreen
make -C vslib
make -C vstring
make -C vfu

Voila!


-- 

"While some hold that perfection is the enemy of the good,
 I've found that it is only in its pursuit that one avoids the
mediocre."

Larry De Coste ***@***.***>
Cochabama BOLIVIA / Pawtucket RI EE.UU.
WhatsApp/Signal/Txt: +1(401) 275-3712

**Comment by andy5995** [comment]
Hello again @LarryDC :)

Thank you for the insight. I don't see that pull and build script you mentioned. Where is that located?

>sudo make install -C yascreen

I think @cade-vs wants the process to not require that. I'm sure that would fix the workflow here in this PR, like you said, but I'm guessing that cade will want to edit the Makefile to find yascreen.h when yascreen is not installed.

**Comment by LarryDC** [comment]
Good night Andy,

On Mon, 06 Feb 2023 18:13:28 -0800

Andy Alt ***@***.***> wrote among other things:

|> Good night Andy, On Mon, 06 Feb 2023 17:49:03 -0800 Andy Alt
|> ***@***.***> wrote among other things: ***@***.*** I've tried a
|> few different things to get this working, but |still having
|> troubles. You might wanna just merge this and then make |any
|> changes you find necessary. | |With regard to the clang
|> `ftlo=auto` error, have a look at this for |a possible fix: |
|> ***@***.***(https://github.com/bbonev/yascreen/commit/59a83fdcaa6cb72ebe1fc3f939c7d99fea024a94)
|> || My 2 cents: All that was necessary was add a line to:
|> || "./pull-and-build-vfu.sh" To compile both vfu & vfu.yas here
|> || (On Debian Testing) I just added the line: sudo make install -C
|> || yascreen after the line: make -C yascreen Or if that's not
|> || clear. The make lines at the end of the file should be: make -C
|> || yascreen sudo make install -C yascreen make -C vslib make -C
|> || vstring make -C vfu Voila! […](#) -- "While some hold that
|> || perfection is the enemy of the good, I've found that it is only
|> || in its pursuit that one avoids the mediocre." Larry De Coste
|> || ***@***.***> Cochabama BOLIVIA / Pawtucket RI EE.UU.
|> || WhatsApp/Signal/Txt: +1(401) 275-3712
|
|Hello again @LarryDC :)
|
|Thank you for the insight. I don't see that pull and build script
|you mentioned. Where is that located?

wget https://cade.noxrun.com/projects/vfu/pull-and-build-vfu.sh
chmod +x ./pull-and-build-vfu.sh
  ./pull-and-build-vfu.sh

|
|>sudo make install -C yascreen
|
|I think @cade-vs wants the process to not require that. I'm sure
|that would fix the workflow here in this PR, like you said, but I'm
|guessing that cade will want to edit the Makefile to find yascreen.h
|when yascreen is not installed.
|
That's way beyond me.  Thanks for your efforts.

Larry



-- 

"While some hold that perfection is the enemy of the good,
 I've found that it is only in its pursuit that one avoids the
mediocre."

Larry De Coste ***@***.***>
Cochabama BOLIVIA / Pawtucket RI EE.UU.
WhatsApp/Signal/Txt: +1(401) 275-3712

**Pull request merged**
